# Generated by Django 2.2 on 2020-04-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hn_users", "0001_initial"),
        ("links", "0003_auto_20200419_1601"),
    ]

    operations = [
        migrations.RenameModel(old_name="Voting", new_name="Vote",),
    ]
