# Generated by Django 2.2 on 2020-04-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hn_users", "0001_initial"),
        ("links", "0004_auto_20200419_1607"),
    ]

    operations = [
        migrations.AlterModelOptions(name="vote", options={},),
        migrations.AlterUniqueTogether(
            name="vote", unique_together={("user", "link")},
        ),
    ]
